# yamllint disable-file
# Answer file maintained by Copier for: https://github.com/KyleKing/calcipy_template
# Check into version control. Edit by re-running copier and changing responses to the questions
_commit: 0.3.4
_src_path: gh:KyleKing/calcipy_template
author_email: dev.act.kyle@gmail.com
author_name: Kyle King
author_username: kyleking
cname: dash_charts.kyleking.me
codecov_token: d414dacb-5b8d-4c0b-94e1-42fe8393187d
copyright_date: '2021'
doc_dir: docs
install_extras: null
package_name_py: dash_charts
project_description: Python package for Plotly/Dash apps with support for multi-page,
  modules, and new charts such as Pareto with an Object Orient Approach
project_name: dash_charts
repository_namespace: kyleking
repository_provider: https://github.com
