---
# see https://pyup.io/docs/configuration/ for all available options

# configure updates globally
# default: all
# allowed: all, insecure, false
update: insecure

# configure dependency pinning globally
# default: true
# allowed: true, false
pin: false

# set the default branch
# default: empty, the default branch on GitHub
# branch: dev

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every month"

# search for requirement files
# default: true
# allowed: true, false
search: true

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
# requirements:
#   - requirements/staging.txt:
#       update: all
#       pin: true

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
# label_prs: update

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
assignees:
 - kyleking

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix: pyup/

# set a global prefix for PRs
# default: empty
pr_prefix: "build:"

# allow to close stale PRs
# default: true
close_prs: true
