[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.commitizen]
name = "cz_legacy"
change_type_order = [
    "BREAKING CHANGE", "Feat", "Fix", "Refactor", "Perf",
    "New (Old)", "Change (Old)", "Fix (Old)",
]
version = "0.1.0a0"
tag_format = "2021.$version"
version_files = [ "pyproject.toml", "calcipy/__init__.py",]

[tool.commitizen.cz_legacy_map]
Chg = "Change (Old)"
Fix = "Fix (Old)"
New = "New (Old)"

[tool.isort]
balanced_wrapping = true
default_section = "THIRDPARTY"
force_grid_wrap = 0
length_sort = false
line_length = 120

[tool.poetry]
name = "dash_charts"
version = "0.1.0a0"
description = "Python package for OOP of Plotly/Dash apps and custom templates"
license = "Unlicense"
authors = [ "Kyle King <dev.act.kyle@gmail.com>",]
maintainers = []
repository = "https://github.com/kyleking/dash_charts"
documentation = "https://github.com/kyleking/dash_charts"
readme = "README.md"
include = [ "LICENSE.md",]
keywords = [ "dash", ]
classifiers = [
    # https://pypi.org/classifiers/
    # And based on: https://github.com/plotly/dash/blob/dev/setup.py#L43
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Web Environment",
    "Framework :: Dash",
    "Framework :: Flask",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Manufacturing",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Database :: Front-Ends",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Widget Sets",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kyleking/dash_charts/issues"

[tool.poetry.dependencies]
python = "^3.8,<3.9"
cerberus = "*"
dash = "*"
dash-bootstrap-components = "*"
dataset = "*"
dominate = "*"
implements = "*"
lxml = "*"
markdown = "*"
Palettable = "*"
pandas = "*"
psutil = "*"
python-box = "*"
scipy = "*"

# matplotlib - See: https://github.com/plotly/plotly.py/issues/1568
matplotlib = {version = "<3.2", optional = true}

[tool.poetry.dependencies.calcipy]
git = "https://github.com/kyleking/calcipy.git"
branch = "dev/development"

[tool.poetry.dev-dependencies.calcipy]
git = "https://github.com/kyleking/calcipy.git"
branch = "dev/development"
extras = [ "dev", "lint", "test", "commitizen_legacy"]

[tool.poetry.dev-dependencies]
astor = "*"
jsonpickle = "*"

# TODO: Try these additional and potentially useful dependencies
typeguard = "*"
# ...
datasette = "*"
datasette-vega = "*"
pendulum = "*"
sqlite-utils = "*"
# ...
great-expectations = "*"

# Experimental dependencies
archan = {git = "https://github.com/pawamoy/archan.git"}
dependenpy = "^3.3.0"
archan-pylint = {git = "https://github.com/pawamoy/archan-pylint"}

[tool.poetry.dev-dependencies.dash]
extras = [ "testing",]
version = "^1.16"

[tool.poetry.extras]
matplotlib = [ "matplotlib",]
