[build-system]
requires = [ "poetry-core>=1.0",]
build-backend = "poetry.core.masonry.api"

[tool.isort]
balanced_wrapping = true
default_section = "THIRDPARTY"
force_grid_wrap = 0
length_sort = false
line_length = 120

[tool.poetry]
name = "dash_charts"
version = "0.0.5"
description = "Python package for OOP of Plotly/Dash apps and custom templates"
license = "MIT"
authors = [ "Kyle King <https://github.com/KyleKing>",]
maintainers = []
readme = "README.md"
repository = "https://github.com/kyleking/dash_charts"
documentation = "https://kyleking.me/dash_charts/"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kyleking/dash_charts/issues"

[tool.poetry.dependencies]
python = "^3.8,<3.9"
cerberus = "*"
dash = "*"
dash-bootstrap-components = "*"
dataset = "*"
dominate = "*"
implements = "*"
markdown = "*"
matplotlib = {version = "<3.2", optional = true}
Palettable = "*"
pandas = "*"
psutil = "*"
scipy = "*"
archan = {git = "https://github.com/pawamoy/archan.git"}

[tool.poetry.dependencies.calcipy]
git = "https://github.com/KyleKing/calcipy.git"
branch = "main"

[tool.poetry.dev-dependencies]
astor = "*"
dash-dev = {git = "https://github.com/KyleKing/dash_dev.git", rev = "main"}
jsonpickle = "*"

# Experimental dependencies
dependenpy = "^3.3.0"
archan-pylint = {git = "https://github.com/pawamoy/archan-pylint"}

[tool.poetry.dev-dependencies.dash]
extras = [ "testing",]
version = "^1.16"
